#!/bin/bash

# Function to check the service status and format the output
check_service_status() {
    local service=$1
    status=$(systemctl is-active "$service")
    if [ "$status" == "active" ]; then
        echo -n " ${service}: 🟢 active  "
    else
        echo -n " ${service}: 🔻 inactive  "
    fi
}

# Display header
echo "Services running:"

# Check and display the status for each service in a compact format
check_service_status "smb"  # Samba
check_service_status "plexmediaserver"  # Plex
echo # New line
check_service_status "sshguard"  # SSH Guard
check_service_status "rsync"  # RSync
echo # New line
check_service_status "ufw"  # UFW
check_service_status "apcupsd"  # APC UPS Daemon
echo # New line
check_service_status "postgresql"  # PostgreSQL
check_service_status "redis"  # Redis
echo # New line